import { db } from "./db";
import { 
  users, 
  vendors, 
  categories, 
  products,
  type InsertUser,
  type InsertVendor,
  type InsertCategory,
  type InsertProduct
} from "@shared/schema";
import bcrypt from "bcrypt";

const productImages = {
  womensDresses: [
    "/products/professional_female__a355dcb0.jpg",
    "/products/professional_female__6f7d1703.jpg",
    "/products/professional_female__1477c2e1.jpg",
    "/products/professional_female__f5a8792b.jpg",
    "/products/professional_female__4aa4c205.jpg",
  ],
  mensFormal: [
    "/products/professional_male_fa_8d5a5494.jpg",
    "/products/professional_male_fa_d1c96d83.jpg",
    "/products/professional_male_fa_b7386462.jpg",
    "/products/professional_male_fa_8896f768.jpg",
    "/products/professional_male_fa_92f7ca2d.jpg",
  ],
  casualWear: [
    "/products/professional_model_w_b2a111b5.jpg",
    "/products/professional_model_w_59ae9a1c.jpg",
    "/products/professional_model_w_70d03694.jpg",
    "/products/professional_model_w_ecdc0a0c.jpg",
    "/products/professional_model_w_25ec85be.jpg",
  ],
  ethnicWear: [
    "/products/professional_model_w_2a9ae38d.jpg",
    "/products/professional_model_w_decc3e22.jpg",
    "/products/professional_model_w_a6bde1f4.jpg",
    "/products/professional_model_w_98b97136.jpg",
    "/products/professional_model_w_b7d48e4c.jpg",
  ],
  businessAttire: [
    "/products/professional_fashion_8c26fe85.jpg",
    "/products/professional_fashion_b039c8cd.jpg",
    "/products/professional_fashion_fba96084.jpg",
    "/products/professional_fashion_c959ef3e.jpg",
    "/products/professional_fashion_266073f0.jpg",
    "/products/professional_fashion_d4387add.jpg",
    "/products/professional_fashion_a7cc6e50.jpg",
    "/products/professional_fashion_d3fa9cfc.jpg",
    "/products/professional_fashion_4c9feac7.jpg",
    "/products/professional_fashion_e9bcc690.jpg",
  ],
  elegantOutfits: [
    "/products/professional_model_w_4d33a1a5.jpg",
    "/products/professional_model_w_d1575dc2.jpg",
    "/products/professional_model_w_10ca998c.jpg",
    "/products/professional_model_w_b3f961fd.jpg",
    "/products/professional_model_w_d65cdd43.jpg",
    "/products/professional_model_w_0ba25810.jpg",
    "/products/professional_model_w_1ee6a9e7.jpg",
    "/products/professional_model_w_2737cf28.jpg",
    "/products/professional_model_w_b147a678.jpg",
    "/products/professional_model_w_7dc4c27c.jpg",
  ],
};

async function seed() {
  console.log("Starting database seed...");

  // Clear existing data
  console.log("Clearing existing data...");
  await db.delete(products);
  await db.delete(categories);
  await db.delete(vendors);
  await db.delete(users);

  // Create admin user
  const hashedPassword = await bcrypt.hash("admin123", 10);
  const [adminUser] = await db.insert(users).values({
    email: "admin@textile.com",
    password: hashedPassword,
    fullName: "Admin User",
    role: "admin",
    phone: "+91 9876543210",
  } as InsertUser).returning();
  console.log("Created admin user");

  // Create vendor users and vendors
  const vendorData = [
    { name: "Elite Fashion House", business: "Elite Fashion House", gst: "29ABCDE1234F1Z5" },
    { name: "Silk Traditions", business: "Silk Traditions Pvt Ltd", gst: "27FGHIJ5678K2Z3" },
    { name: "Cotton Comfort", business: "Cotton Comfort Co", gst: "33KLMNO9012P3Z1" },
    { name: "Royal Textiles", business: "Royal Textiles India", gst: "19QRSTU3456V4Z9" },
  ];

  const vendorIds: string[] = [];
  for (const vendor of vendorData) {
    const vendorPassword = await bcrypt.hash("vendor123", 10);
    const [vendorUser] = await db.insert(users).values({
      email: vendor.name.toLowerCase().replace(/\s+/g, "") + "@textile.com",
      password: vendorPassword,
      fullName: vendor.name + " Admin",
      role: "vendor",
      phone: "+91 98765" + Math.floor(10000 + Math.random() * 90000),
    } as InsertUser).returning();

    const [vendorProfile] = await db.insert(vendors).values({
      userId: vendorUser.id,
      businessName: vendor.business,
      gstNumber: vendor.gst,
      businessAddress: "123 Textile Market, Mumbai, Maharashtra, India",
      kycStatus: "approved",
      description: `Premium quality textiles and garments from ${vendor.business}`,
      rating: (4 + Math.random()).toFixed(2),
      totalSales: Math.floor(Math.random() * 1000),
    } as InsertVendor).returning();

    vendorIds.push(vendorProfile.id);
  }
  console.log(`Created ${vendorIds.length} vendors`);

  // Create categories
  const categoryData = [
    { name: "Women's Wear", slug: "womens-wear", description: "Elegant dresses and women's fashion", image: productImages.womensDresses[0] },
    { name: "Casual Wear", slug: "casual-wear", description: "Comfortable everyday clothing", image: productImages.casualWear[0] },
    { name: "Ethnic Wear", slug: "ethnic-wear", description: "Traditional ethnic clothing", image: productImages.ethnicWear[0] },
  ];

  const categoryIds: Record<string, string> = {};
  for (const cat of categoryData) {
    const [category] = await db.insert(categories).values(cat as InsertCategory).returning();
    categoryIds[cat.slug] = category.id;
  }
  console.log(`Created ${Object.keys(categoryIds).length} categories`);

  // Create products
  const productsData = [
    // Women's Dresses
    {
      name: "Elegant Silk Dress",
      slug: "elegant-silk-dress",
      description: "Premium silk dress perfect for formal occasions. Features a flattering silhouette and luxurious fabric.",
      categorySlug: "womens-wear",
      fabric: "Silk",
      price: "2499.00",
      moq: 1,
      stock: 100,
      images: [productImages.womensDresses[0], productImages.womensDresses[1]],
      colors: ["Black", "Navy Blue", "Burgundy"],
      sizes: ["XS", "S", "M", "L", "XL"],
      featured: true,
    },
    {
      name: "Designer Cocktail Dress",
      slug: "designer-cocktail-dress",
      description: "Contemporary cocktail dress with modern design elements. Perfect for evening events.",
      categorySlug: "womens-wear",
      fabric: "Polyester Blend",
      price: "1899.00",
      moq: 1,
      stock: 80,
      images: [productImages.womensDresses[2], productImages.womensDresses[3]],
      colors: ["Red", "Emerald Green", "Royal Blue"],
      sizes: ["S", "M", "L", "XL"],
      featured: true,
    },
    {
      name: "Classic A-Line Dress",
      slug: "classic-a-line-dress",
      description: "Timeless A-line dress suitable for various occasions. Comfortable and stylish.",
      categorySlug: "womens-wear",
      fabric: "Cotton Blend",
      price: "1299.00",
      moq: 1,
      stock: 150,
      images: [productImages.womensDresses[4], productImages.womensDresses[0]],
      colors: ["White", "Beige", "Light Pink"],
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    // Men's Formal
    {
      name: "Premium Formal Shirt",
      slug: "premium-formal-shirt",
      description: "High-quality formal shirt crafted from premium cotton. Perfect for business and formal occasions.",
      categorySlug: "mens-formal",
      fabric: "Cotton",
      price: "1499.00",
      moq: 1,
      stock: 200,
      images: [productImages.mensFormal[0], productImages.mensFormal[1]],
      colors: ["White", "Light Blue", "Lavender"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: true,
    },
    {
      name: "Executive Dress Shirt",
      slug: "executive-dress-shirt",
      description: "Sophisticated dress shirt with wrinkle-resistant fabric. Ideal for executives and professionals.",
      categorySlug: "mens-formal",
      fabric: "Cotton Blend",
      price: "1799.00",
      moq: 1,
      stock: 120,
      images: [productImages.mensFormal[2], productImages.mensFormal[3]],
      colors: ["White", "Sky Blue", "Grey"],
      sizes: ["M", "L", "XL", "XXL"],
      featured: true,
    },
    {
      name: "Classic Formal Shirt",
      slug: "classic-formal-shirt",
      description: "Essential formal shirt for everyday office wear. Comfortable fit and easy maintenance.",
      categorySlug: "mens-formal",
      fabric: "Polyester Cotton",
      price: "999.00",
      moq: 1,
      stock: 250,
      images: [productImages.mensFormal[4], productImages.mensFormal[0]],
      colors: ["White", "Light Blue", "Pink"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    // Casual Wear
    {
      name: "Comfort Cotton T-Shirt",
      slug: "comfort-cotton-tshirt",
      description: "Ultra-soft cotton t-shirt for everyday comfort. Perfect for casual outings.",
      categorySlug: "casual-wear",
      fabric: "100% Cotton",
      price: "599.00",
      moq: 1,
      stock: 300,
      images: [productImages.casualWear[0], productImages.casualWear[1]],
      colors: ["White", "Black", "Grey", "Navy"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: true,
    },
    {
      name: "Casual Polo Shirt",
      slug: "casual-polo-shirt",
      description: "Classic polo shirt combining comfort with style. Suitable for smart casual occasions.",
      categorySlug: "casual-wear",
      fabric: "Pique Cotton",
      price: "899.00",
      moq: 1,
      stock: 180,
      images: [productImages.casualWear[2], productImages.casualWear[3]],
      colors: ["Navy", "Green", "Maroon", "Grey"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    {
      name: "Relaxed Fit Casual Shirt",
      slug: "relaxed-fit-casual-shirt",
      description: "Comfortable casual shirt with relaxed fit. Perfect for weekend wear.",
      categorySlug: "casual-wear",
      fabric: "Linen Blend",
      price: "1199.00",
      moq: 1,
      stock: 140,
      images: [productImages.casualWear[4], productImages.casualWear[0]],
      colors: ["Beige", "Light Blue", "Olive"],
      sizes: ["M", "L", "XL", "XXL"],
      featured: false,
    },
    // Ethnic Wear
    {
      name: "Traditional Silk Saree",
      slug: "traditional-silk-saree",
      description: "Exquisite silk saree with traditional design. Perfect for weddings and festivals.",
      categorySlug: "ethnic-wear",
      fabric: "Pure Silk",
      price: "3999.00",
      moq: 1,
      stock: 60,
      images: [productImages.ethnicWear[0], productImages.ethnicWear[1]],
      colors: ["Royal Blue", "Red", "Green", "Purple"],
      sizes: ["One Size"],
      featured: true,
    },
    {
      name: "Designer Kurti",
      slug: "designer-kurti",
      description: "Contemporary designer kurti with traditional elements. Versatile ethnic wear.",
      categorySlug: "ethnic-wear",
      fabric: "Cotton Silk",
      price: "1499.00",
      moq: 1,
      stock: 120,
      images: [productImages.ethnicWear[2], productImages.ethnicWear[3]],
      colors: ["Pink", "Blue", "Green", "Yellow"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: true,
    },
    {
      name: "Ethnic Palazzo Set",
      slug: "ethnic-palazzo-set",
      description: "Comfortable palazzo set with ethnic prints. Modern take on traditional wear.",
      categorySlug: "ethnic-wear",
      fabric: "Rayon",
      price: "1799.00",
      moq: 1,
      stock: 100,
      images: [productImages.ethnicWear[4], productImages.ethnicWear[0]],
      colors: ["Multicolor", "Black", "Maroon"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    // More Women's Wear
    {
      name: "Business Blazer Dress",
      slug: "business-blazer-dress",
      description: "Professional blazer-style dress for corporate settings. Modern and sophisticated.",
      categorySlug: "womens-wear",
      fabric: "Wool Blend",
      price: "3299.00",
      moq: 1,
      stock: 70,
      images: [productImages.businessAttire[0], productImages.businessAttire[1]],
      colors: ["Black", "Navy", "Charcoal"],
      sizes: ["S", "M", "L", "XL"],
      featured: true,
    },
    {
      name: "Office Midi Dress",
      slug: "office-midi-dress",
      description: "Elegant midi dress perfect for professional environments. Comfortable and stylish.",
      categorySlug: "womens-wear",
      fabric: "Polyester Blend",
      price: "1999.00",
      moq: 1,
      stock: 90,
      images: [productImages.businessAttire[2], productImages.businessAttire[3]],
      colors: ["Burgundy", "Teal", "Black"],
      sizes: ["XS", "S", "M", "L", "XL"],
      featured: false,
    },
    {
      name: "Executive Sheath Dress",
      slug: "executive-sheath-dress",
      description: "Classic sheath dress for the modern professional woman. Timeless elegance.",
      categorySlug: "womens-wear",
      fabric: "Cotton Blend",
      price: "2199.00",
      moq: 1,
      stock: 85,
      images: [productImages.businessAttire[4], productImages.businessAttire[5]],
      colors: ["Black", "Navy Blue", "Olive"],
      sizes: ["S", "M", "L", "XL"],
      featured: false,
    },
    {
      name: "Formal Pencil Dress",
      slug: "formal-pencil-dress",
      description: "Fitted pencil dress for formal occasions. Sophisticated and flattering.",
      categorySlug: "womens-wear",
      fabric: "Crepe",
      price: "2399.00",
      moq: 1,
      stock: 75,
      images: [productImages.businessAttire[6], productImages.businessAttire[7]],
      colors: ["Black", "Wine Red", "Navy"],
      sizes: ["XS", "S", "M", "L"],
      featured: false,
    },
    {
      name: "Professional Wrap Dress",
      slug: "professional-wrap-dress",
      description: "Versatile wrap dress suitable for office and events. Comfortable fit.",
      categorySlug: "womens-wear",
      fabric: "Jersey",
      price: "1799.00",
      moq: 1,
      stock: 95,
      images: [productImages.businessAttire[8], productImages.businessAttire[9]],
      colors: ["Navy", "Burgundy", "Forest Green"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    // Elegant Outfits
    {
      name: "Evening Gown",
      slug: "evening-gown",
      description: "Luxurious evening gown for special occasions. Exquisite design and premium fabric.",
      categorySlug: "womens-wear",
      fabric: "Silk Satin",
      price: "4999.00",
      moq: 1,
      stock: 40,
      images: [productImages.elegantOutfits[0], productImages.elegantOutfits[1]],
      colors: ["Black", "Emerald", "Burgundy"],
      sizes: ["XS", "S", "M", "L"],
      featured: true,
    },
    {
      name: "Cocktail Party Dress",
      slug: "cocktail-party-dress",
      description: "Stunning cocktail dress perfect for parties and celebrations. Eye-catching design.",
      categorySlug: "womens-wear",
      fabric: "Chiffon",
      price: "2899.00",
      moq: 1,
      stock: 65,
      images: [productImages.elegantOutfits[2], productImages.elegantOutfits[3]],
      colors: ["Red", "Royal Blue", "Gold"],
      sizes: ["S", "M", "L", "XL"],
      featured: true,
    },
    {
      name: "Formal Ball Gown",
      slug: "formal-ball-gown",
      description: "Elegant ball gown for formal events. Makes a statement.",
      categorySlug: "womens-wear",
      fabric: "Taffeta",
      price: "5499.00",
      moq: 1,
      stock: 30,
      images: [productImages.elegantOutfits[4], productImages.elegantOutfits[5]],
      colors: ["Black", "Navy Blue", "Champagne"],
      sizes: ["XS", "S", "M", "L"],
      featured: false,
    },
    {
      name: "Maxi Evening Dress",
      slug: "maxi-evening-dress",
      description: "Flowing maxi dress for evening occasions. Graceful and elegant.",
      categorySlug: "womens-wear",
      fabric: "Georgette",
      price: "3299.00",
      moq: 1,
      stock: 55,
      images: [productImages.elegantOutfits[6], productImages.elegantOutfits[7]],
      colors: ["Plum", "Teal", "Black"],
      sizes: ["S", "M", "L", "XL"],
      featured: false,
    },
    {
      name: "Sequin Party Dress",
      slug: "sequin-party-dress",
      description: "Dazzling sequin dress for parties. Glamorous and sparkly.",
      categorySlug: "womens-wear",
      fabric: "Sequin Fabric",
      price: "3799.00",
      moq: 1,
      stock: 50,
      images: [productImages.elegantOutfits[8], productImages.elegantOutfits[9]],
      colors: ["Gold", "Silver", "Rose Gold"],
      sizes: ["S", "M", "L"],
      featured: true,
    },
    // Additional Men's Formal
    {
      name: "Slim Fit Dress Shirt",
      slug: "slim-fit-dress-shirt",
      description: "Modern slim fit dress shirt for a contemporary look. Sharp and stylish.",
      categorySlug: "mens-formal",
      fabric: "Cotton",
      price: "1599.00",
      moq: 1,
      stock: 160,
      images: [productImages.mensFormal[1], productImages.mensFormal[2]],
      colors: ["White", "Light Pink", "Lavender"],
      sizes: ["S", "M", "L", "XL"],
      featured: false,
    },
    {
      name: "Non-Iron Business Shirt",
      slug: "non-iron-business-shirt",
      description: "Wrinkle-free business shirt for busy professionals. Low maintenance.",
      categorySlug: "mens-formal",
      fabric: "Polyester Cotton",
      price: "1399.00",
      moq: 1,
      stock: 180,
      images: [productImages.mensFormal[3], productImages.mensFormal[4]],
      colors: ["White", "Light Blue", "Grey"],
      sizes: ["M", "L", "XL", "XXL"],
      featured: false,
    },
    {
      name: "Premium Oxford Shirt",
      slug: "premium-oxford-shirt",
      description: "High-quality Oxford cloth shirt. Classic and durable.",
      categorySlug: "mens-formal",
      fabric: "Oxford Cotton",
      price: "1899.00",
      moq: 1,
      stock: 140,
      images: [productImages.mensFormal[0], productImages.mensFormal[1]],
      colors: ["White", "Sky Blue", "Pink"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    // Additional Casual Wear
    {
      name: "Weekend Casual Shirt",
      slug: "weekend-casual-shirt",
      description: "Comfortable casual shirt for relaxed weekends. Easy to wear.",
      categorySlug: "casual-wear",
      fabric: "Cotton Linen",
      price: "1099.00",
      moq: 1,
      stock: 150,
      images: [productImages.casualWear[1], productImages.casualWear[2]],
      colors: ["White", "Beige", "Light Grey"],
      sizes: ["M", "L", "XL", "XXL"],
      featured: false,
    },
    {
      name: "Casual Button-Down",
      slug: "casual-button-down",
      description: "Versatile button-down shirt for casual occasions. Smart casual style.",
      categorySlug: "casual-wear",
      fabric: "Cotton",
      price: "999.00",
      moq: 1,
      stock: 170,
      images: [productImages.casualWear[3], productImages.casualWear[4]],
      colors: ["Denim Blue", "Olive", "Maroon"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    {
      name: "Henley T-Shirt",
      slug: "henley-tshirt",
      description: "Classic Henley style t-shirt. Casual and comfortable.",
      categorySlug: "casual-wear",
      fabric: "Cotton Jersey",
      price: "799.00",
      moq: 1,
      stock: 200,
      images: [productImages.casualWear[0], productImages.casualWear[1]],
      colors: ["Grey", "Navy", "Black", "White"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    // Additional Ethnic Wear
    {
      name: "Embroidered Anarkali",
      slug: "embroidered-anarkali",
      description: "Beautiful embroidered Anarkali suit. Traditional craftsmanship.",
      categorySlug: "ethnic-wear",
      fabric: "Georgette",
      price: "2999.00",
      moq: 1,
      stock: 70,
      images: [productImages.ethnicWear[1], productImages.ethnicWear[2]],
      colors: ["Pink", "Blue", "Peach"],
      sizes: ["S", "M", "L", "XL"],
      featured: false,
    },
    {
      name: "Cotton Kurta Set",
      slug: "cotton-kurta-set",
      description: "Comfortable cotton kurta with pants. Perfect for daily wear.",
      categorySlug: "ethnic-wear",
      fabric: "Cotton",
      price: "1199.00",
      moq: 1,
      stock: 130,
      images: [productImages.ethnicWear[3], productImages.ethnicWear[4]],
      colors: ["White", "Cream", "Light Blue"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    {
      name: "Printed Palazzo Suit",
      slug: "printed-palazzo-suit",
      description: "Trendy printed suit with palazzo pants. Contemporary ethnic fashion.",
      categorySlug: "ethnic-wear",
      fabric: "Rayon",
      price: "1599.00",
      moq: 1,
      stock: 110,
      images: [productImages.ethnicWear[0], productImages.ethnicWear[1]],
      colors: ["Floral Print", "Geometric Print"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      featured: false,
    },
    {
      name: "Silk Dupatta Set",
      slug: "silk-dupatta-set",
      description: "Elegant silk kurta with matching dupatta. Festive wear.",
      categorySlug: "ethnic-wear",
      fabric: "Silk",
      price: "2499.00",
      moq: 1,
      stock: 80,
      images: [productImages.ethnicWear[2], productImages.ethnicWear[3]],
      colors: ["Magenta", "Turquoise", "Orange"],
      sizes: ["S", "M", "L", "XL"],
      featured: false,
    },
  ];

  let productCount = 0;
  for (const prod of productsData) {
    const vendorId = vendorIds[Math.floor(Math.random() * vendorIds.length)];
    await db.insert(products).values({
      vendorId,
      name: prod.name,
      slug: prod.slug,
      description: prod.description,
      categoryId: categoryIds[prod.categorySlug],
      fabric: prod.fabric,
      price: prod.price,
      moq: prod.moq,
      stock: prod.stock,
      images: prod.images,
      colors: prod.colors,
      sizes: prod.sizes,
      bulkPricing: null,
      isActive: true,
      featured: prod.featured,
      rating: (4 + Math.random()).toFixed(2),
      reviewCount: Math.floor(Math.random() * 50),
    } as InsertProduct);
    productCount++;
  }

  console.log(`Created ${productCount} products`);
  console.log("Seed completed successfully!");
}

seed()
  .then(() => {
    console.log("✅ Database seeded successfully");
    process.exit(0);
  })
  .catch((error) => {
    console.error("❌ Error seeding database:", error);
    process.exit(1);
  });
